#!/usr/bin/perl -w
use strict;
use Data::Dumper;
$Data::Dumper::Sortkeys = 1;

# AU TY AU BU                         01   main st oak apts
# NA ST BN BT                         B* 85
#
# DR AU TY AU BU                      01   n main st oak apts
# PD NA ST BN BT                      B* 85
#

my %expect = (
    '1/2 N Oak ave chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '1/2 Oak Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '10609 southwest California hwy 2 chelmsford ma usa'
    => 'HOUSE PREDIR EXTRA PRETYP STREET CITY PROV NATION',
    '10609 southwest California hwy 2a chelmsford ma usa'
    => 'HOUSE PREDIR EXTRA PRETYP STREET STREET CITY PROV NATION',
    '10609 southwest hwy 2 chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '10609 southwest hwy 2a chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET STREET CITY PROV NATION',
    '10609 southwest hwy a chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '11YY North main Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 & 27 Oak Street chelmsford ma usa'
    => 'HOUSE EXTRA EXTRA STREET SUFTYP CITY PROV NATION',
    '123 1 Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 1 chelmsford ma usa'
    => 'HOUSE STREET CITY PROV NATION',
    '123 1/2 Ave of the americas blvd chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 1/2 Avenida 1 chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 1/2 Avenida B chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 1/2 Avenida Oak chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 1/2 B Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 1/2 B chelmsford ma usa'
    => 'HOUSE HOUSE STREET CITY PROV NATION',
    '123 1/2 Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 1/2 Terrace Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 8 1/2 street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Avenida 1 & Green Cove chelmsford ma usa'
    => 'HOUSE PRETYP STREET EXTRA EXTRA EXTRA CITY PROV NATION',
    '123 Avenida 1 B chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 Avenida 1 Oak chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 Avenida 1 chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 Avenida B 1 chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 Avenida B D Oak chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET STREET CITY PROV NATION',
    '123 Avenida B Oak chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 Avenida B chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 Avenida Oak B Park chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET STREET CITY PROV NATION',
    '123 Avenida Oak B chelmsford ma usa'
    => 'HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 Avenida Oak Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 B 1 Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B 1 chelmsford ma usa'
    => 'HOUSE HOUSE STREET CITY PROV NATION',
    '123 B Avenida 1 chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 B Avenida D Oak chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 B Avenida D chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 B Avenida Oak D chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET STREET CITY PROV NATION',
    '123 B Avenida Oak chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123 B Beck chelmsford ma usa'
    => 'HOUSE HOUSE STREET CITY PROV NATION',
    '123 B D Oak Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 B D Oak chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET CITY PROV NATION',
    '123 B D Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B D chelmsford ma usa'
    => 'HOUSE HOUSE STREET CITY PROV NATION',
    '123 B North Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B North chelmsford ma usa'
    => 'HOUSE HOUSE STREET CITY PROV NATION',
    '123 B Oak & Park Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 B Oak D chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET CITY PROV NATION',
    '123 B Oak North Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 B Oak Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B Oak Terrace Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 B Oak West chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFDIR CITY PROV NATION',
    '123 B South 1 Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 B South 1 chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    '123 B South Avenida 1 chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '123 B South Avenida D chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '123 B South Avenida Oak chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '123 B South D Oak Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 B South D Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 B South D chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    '123 B South North Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 B South North chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    '123 B South Oak Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 B South Oak Terrace Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 B South Oak chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    '123 B South Terrace Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 B Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B Terrace Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 B Terrace West Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFDIR SUFTYP CITY PROV NATION',
    '123 B Tower Street chelmsford ma usa'
    => 'HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '123 Box road chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 C circle hill drive chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 California state route 1 chelmsford ma usa'
    => 'HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123 California state route 1a chelmsford ma usa'
    => 'HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123 California state route B chelmsford ma usa'
    => 'HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123 Calle anything chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 Circle hill chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 County rd aa chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 E 40 N st chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR SUFTYP CITY PROV NATION',
    '123 E 40N st chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR SUFTYP CITY PROV NATION',
    '123 Forest Park Rd chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Karen e. lane dr chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 M & M road chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 N business 80 chelmsford ma usa'
    => 'HOUSE PREDIR QUALIF STREET CITY PROV NATION',
    '123 N old hwy 80 chelmsford ma usa'
    => 'HOUSE PREDIR QUALIF PRETYP STREET CITY PROV NATION',
    '123 N old hwy 80a chelmsford ma usa'
    => 'HOUSE PREDIR QUALIF PRETYP STREET CITY PROV NATION',
    '123 North Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 North ave of the americas chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '123 North chelmsford ma usa'
    => 'HOUSE STREET CITY PROV NATION',
    '123 Oak & Green chelmsford ma usa'
    => 'HOUSE STREET EXTRA EXTRA CITY PROV NATION',
    '123 Oak 1 Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak B Park Street chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak B Park West chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFDIR CITY PROV NATION',
    '123 Oak B Park chelmsford ma usa'
    => 'HOUSE STREET STREET STREET CITY PROV NATION',
    '123 Oak B Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak B chelmsford ma usa'
    => 'HOUSE STREET STREET CITY PROV NATION',
    '123 Oak North Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 Oak Tower Manor Street chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak Tower Park Street chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak Tower Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Oak chelmsford ma usa'
    => 'HOUSE STREET CITY PROV NATION',
    '123 S 20th w ave chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR SUFTYP CITY PROV NATION',
    '123 South 1 Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South 1 chelmsford ma usa'
    => 'HOUSE PREDIR STREET CITY PROV NATION',
    '123 South 1/2 Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South 3 1/2 Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Avenida 1 West chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET SUFDIR CITY PROV NATION',
    '123 South Avenida 1 chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    '123 South Avenida B Oak chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET STREET CITY PROV NATION',
    '123 South Avenida Oak B chelmsford ma usa'
    => 'HOUSE PREDIR PRETYP STREET STREET CITY PROV NATION',
    '123 South B D Oak Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 South B D Oak chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET CITY PROV NATION',
    '123 South B Oak Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South B Oak chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET CITY PROV NATION',
    '123 South B Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South B Terrace Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South B chelmsford ma usa'
    => 'HOUSE PREDIR STREET CITY PROV NATION',
    '123 South North Oak Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South North Oak chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET CITY PROV NATION',
    '123 South North Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South North chelmsford ma usa'
    => 'HOUSE PREDIR STREET CITY PROV NATION',
    '123 South Oak & East Green chelmsford ma usa'
    => 'HOUSE PREDIR STREET EXTRA EXTRA EXTRA CITY PROV NATION',
    '123 South Oak & Green chelmsford ma usa'
    => 'HOUSE PREDIR STREET EXTRA EXTRA CITY PROV NATION',
    '123 South Oak & Park Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak B Park Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak B Park chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET CITY PROV NATION',
    '123 South Oak B Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak North Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South Oak Terrace Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak Tower Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Oak chelmsford ma usa'
    => 'HOUSE PREDIR STREET CITY PROV NATION',
    '123 South Terrace 1 Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Terrace Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South Tower Manor Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Tower Oak Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South Tower Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 South Tower Terrace Street chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South box hill road chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 South cardboard box road chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 State Route 1 chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 State Route 1a chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 State Route B chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 Terrace 1 Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Terrace Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 Terrace West Street chelmsford ma usa'
    => 'HOUSE STREET SUFDIR SUFTYP CITY PROV NATION',
    '123 Tower Manor Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Tower Oak Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 Tower Street chelmsford ma usa'
    => 'HOUSE STREET SUFTYP CITY PROV NATION',
    '123 Tower Terrace Street chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 box hill road chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 business 80 chelmsford ma usa'
    => 'HOUSE QUALIF STREET CITY PROV NATION',
    '123 cardboard box road chelmsford ma usa'
    => 'HOUSE STREET STREET SUFTYP CITY PROV NATION',
    '123 circle 10 chelmsford ma usa'
    => 'HOUSE PRETYP STREET CITY PROV NATION',
    '123 e circle hill drive chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET SUFTYP CITY PROV NATION',
    '123 hwy i80 chelmsford ma usa'
    => 'HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123 main st hwy 4 chelmsford ma usa'
    => 'HOUSE STREET SUFTYP EXTRA EXTRA CITY PROV NATION',
    '123 n main w chelmsford ma usa'
    => 'HOUSE PREDIR STREET UNITT CITY PROV NATION',
    '123 north box road chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '123 old California hwy 80 chelmsford ma usa'
    => 'HOUSE QUALIF EXTRA PRETYP STREET CITY PROV NATION',
    '123 old California hwy 80a chelmsford ma usa'
    => 'HOUSE QUALIF EXTRA PRETYP STREET CITY PROV NATION',
    '123 old hwy 80 chelmsford ma usa'
    => 'HOUSE QUALIF PRETYP STREET CITY PROV NATION',
    '123 old hwy 80a chelmsford ma usa'
    => 'HOUSE QUALIF PRETYP STREET CITY PROV NATION',
    '123 old north stamford rd chelmsford ma usa'
    => 'HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123 s ave n chelmsford ma usa'
    => 'HOUSE STREET SUFTYP SUFDIR CITY PROV NATION',
    '123 us rt 56w chelmsford ma usa'
    => 'HOUSE PRETYP STREET SUFDIR CITY PROV NATION',
    '123A edward h ross drive chelmsford ma usa'
    => 'HOUSE HOUSE STREET STREET STREET SUFTYP CITY PROV NATION',
    '123E 40 N st chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR SUFTYP CITY PROV NATION',
    '123E 40N st chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR SUFTYP CITY PROV NATION',
    '123a California state route 1 chelmsford ma usa'
    => 'HOUSE HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123a California state route 1a chelmsford ma usa'
    => 'HOUSE HOUSE EXTRA PRETYP STREET CITY PROV NATION',
    '123a state route 1 chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '123a state route 1a chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '16 will o wisp street expy chelmsford ma usa'
    => 'HOUSE STREET STREET STREET STREET SUFTYP CITY PROV NATION',
    '20YY11 North main Street chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    '26 w 415 oak dr chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '26 w 415 pky dr chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '26w415 oak dr chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '26w415 pky dr chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    '3643 apt 16 n main st chelmsford ma usa'
    => 'HOUSE UNITH UNITT PREDIR STREET SUFTYP CITY PROV NATION',
    '3643 apt 16 southmont dr chelmsford ma usa'
    => 'HOUSE UNITH UNITT STREET SUFTYP CITY PROV NATION',
    '3643 rr 1 southmont drive chelmsford ma usa'
    => 'HOUSE RR RR STREET SUFTYP CITY PROV NATION',
    '4268 1 hwy 2 chelmsford ma usa'
    => 'HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    '5439 S 500 Harriet chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET CITY PROV NATION',
    '5439 S 500 W chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '5439 S 500W chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '5439 S fifth w chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '5439S 500 W chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '5439S 500W chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '5439S fifth w chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR CITY PROV NATION',
    '800 N 400 E 1 E chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR UNITT UNITT CITY PROV NATION',
    '800 N 400 E E 1 chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR UNITT UNITT CITY PROV NATION',
    '800N 400E 1 E chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR UNITT UNITT CITY PROV NATION',
    '800N 400E E 1 chelmsford ma usa'
    => 'HOUSE PREDIR STREET SUFDIR UNITT UNITT CITY PROV NATION',
    '806 n march d sea ave pike chelmsford ma usa'
    => 'HOUSE PREDIR STREET STREET STREET STREET SUFTYP CITY PROV NATION',
    'A2-1 s springdale rd chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'N 108 W 60 country club ct chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    'N 108 W 60 hwy 55 chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N 108 W 60 hwy 8a chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N 108 W 60 hwy k chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N 108 W 60 main chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET CITY PROV NATION',
    'N 108 W 60 main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    'N 108 W 60 n hwy 44 chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    'N 108 W 60 n main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'N 108 W60 main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    'N108 W 60 main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    'N108 W 60 s main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'N108 W60 country club ct chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET STREET SUFTYP CITY PROV NATION',
    'N108 W60 hwy 55 chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N108 W60 hwy aa chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N108 W60 hwy k chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PRETYP STREET CITY PROV NATION',
    'N108 W60 main chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET CITY PROV NATION',
    'N108 W60 main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    'N108 W60 n hwy 55 chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PREDIR PRETYP STREET CITY PROV NATION',
    'N108 W60 n main st chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'Rural Route chelmsford ma usa'
    => 'RR CITY PROV NATION',
    'South 123 B Oak chelmsford ma usa'
    => 'PREDIR HOUSE STREET STREET CITY PROV NATION',
    'South 123 B chelmsford ma usa'
    => 'PREDIR HOUSE STREET CITY PROV NATION',
    'YY11 North main Street chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'e 101 n 103 chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    'e101 n103 chelmsford ma usa'
    => 'HOUSE HOUSE PREDIR STREET CITY PROV NATION',
    'us rt 1 280 lafayette rd chelmsford ma usa'
    => 'EXTRA EXTRA HOUSE STREET SUFTYP CITY PROV NATION',
    'w 220 1551 s springdale rd chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'w 220 1551 springdale rd chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION',
    'w220 1551 s springdale rd chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE PREDIR STREET SUFTYP CITY PROV NATION',
    'w220 1551 springdale rd chelmsford ma usa'
    => 'HOUSE HOUSE HOUSE STREET SUFTYP CITY PROV NATION'
          );


my %itok = (
           'A1' => 'SINGLE',
           'A2' => 'DOUBLE',
           'A3' => 'WORD',
           'AM' => 'AMPERS',
           'AN' => 'MIXED',
           'AU' => 'WORD',
           'B*' => '[building]',
           'BU' => 'BUILDT',
           'BX' => 'BOXH',
           'D1' => 'DIRECT',
           'DA' => 'DASH',
           'DR' => 'DIRECT',
           'EX' => 'QUALIF',
           'FC' => 'FRACT',
           'H*' => '[house]',
           'HR' => 'ROAD',
           'MP' => 'MILE',
           'N*' => '[number]',
           'NU' => 'NUMBER',
           'OT' => 'ORD',
           'P*' => '[pobox]',
           'PT' => 'TYPE',
           'R*' => '[ruralroute]',
           'RR' => 'RR',
           'SA' => 'PROV',
           'T*' => '[streetname]',
           'TY' => 'TYPE',
           'W*' => '[within]',
           'WD' => 'UNITH',
           'WI' => 'UNITT',
         );

my %otok = (
           '1P' => 'HOUSE',
           'B*' => '@building',
           'BD' => 'BLDNG',
           'BI' => 'BLDNG',
           'BN' => 'BLDNG',
           'BS' => 'BLDNG',
           'BT' => 'BLDNG',
           'BX' => 'BOXH',
           'BY' => 'BLDNG',
           'DB' => 'BLDNG',
           'EI' => 'EXTRA',
           'EX' => 'QUALIF',
           'H*' => '@house',
           'H1' => 'HOUSE',
           'H2' => 'HOUSE',
           'HN' => 'HOUSE',
           'HS' => 'HOUSE',
           'NA' => 'STREET',
           'NB' => 'BLDNG',
           'P*' => '@pobox',
           'P1' => 'HOUSE',
           'P2' => 'HOUSE',
           'PD' => 'PREDIR',
           'PT' => 'PRETYP',
           'R*' => '@ruralroute',
           'RN' => 'RR',
           'RR' => 'RR',
           'SD' => 'SUFDIR',
           'ST' => 'SUFTYP',
           'T*' => '@streetname',
           'TB' => 'BLDNG',
           'W*' => '@within',
           'WD' => 'UNITH',
           'WI' => 'UNITT',
           'XN' => 'BOXT',
          );

sub Usage {
    die "Usage: convert-patterns patterns.dat\n";
}

my $file = shift @ARGV || Usage();

open(IN, $file) || die "Error: failed to open '$file' : $!\n";

my %intok = ();
my %outtok = ();
my %pattern = ();

while (!eof(IN)) {
    my $in = <IN>;
    chomp($in);
    my @ipat = getpat(substr($in, 1, 34));
    my $example = substr($in, 42);
    my $out = <IN>;
    my @opat = getpat(substr($out, 1, 34));
    my $typ  = substr($out, 37, 2);
    my $pri  = substr($out, 40, 2);
    my $lang = substr($out, 56, 1);
    my $usf  = substr($out, 57, 1);
    my $excl = substr($out, 58, 1);
    $out = <IN>; # skip over blank line
    for my $x (@ipat) {
        $intok{$x}++;
    }
    for my $x (@opat) {
        $outtok{$x}++;
    }
    push @{$pattern{$typ}}, { ipat => \@ipat,
                              opat => \@opat,
                              type => $typ,
                              pri  => $pri,
                              lang => $lang,
                              usf  => $usf,
                              excl => $excl,
                              exam => $example,
                            };
}
close(IN);

#print Data::Dumper->Dump([\%intok, \%outtok, \%pattern], [qw(intok outtok pattern)]);


my $fail = 0;
my $match = 0;

for my $x (sort keys %expect) {
    my $addr = $x;
    my $cmd = "./t2 lex-usa.txt ../../data/grammar/test2.grammar '$addr' 2>/dev/null | grep BEST";
    my $res = `$cmd`;
    $res =~ s/^BEST: |\s*$//g;
    my $expect = $expect{$x};

    if ($res eq $expect) {
        $match++;
    }
    else {
        print "$addr\nEXPT: $expect\nBEST: $res\n\n";
        $fail++;
    }
}

print "SUMMARY: MATCH: $match, FAILED: $fail\n";

exit;

#for my $x (@{$pattern{'H*'}}, @{$pattern{'H+'}}) {
for my $x (@{$pattern{'H*'}}) {
    #print $x->{exam}, "\t=>\t", join(' ', map { $itok{$_} } @{$x->{ipat}}), "\n";}
    my $addr = $x->{exam};
    $addr =~ s/^\s*|\s*$//g;
    $addr .= " chelmsford ma usa";
    my $cmd = "./t2 lex-usa.txt ../../data/grammar/test2.grammar '$addr' 2>/dev/null | grep BEST";
    my $res = `$cmd`;
    $res =~ s/^BEST: |\s*$//g;
    my $expect = join(' ', map { $otok{$_} } @{$x->{opat}}) . " CITY PROV NATION";

    if ($res eq $expect) {
        $match++;
    }
    else {
        print "$addr\nEXPT: $expect\nBEST: $res\n\n";
        $fail++;
    }
}

print "SUMMARY: MATCH: $match, FAILED: $fail\n";

exit;

sub getpat {
    my $s = shift;
    $s =~ s/^\s*|\s*$//g;
    return split(/\s/, $s);
}


=pod
$intok = {
           'A1' => 257, SINGLE
           'A2' => 20,  DOUBLE
           'A3' => 4,   WORD
           'AM' => 21,  AMPERS
           'AN' => 21,  MIXED
           'AU' => 282, WORD
           'B*' => 7,   [building]
           'BU' => 193, BUILDT
           'BX' => 19,  BOXH
           'D1' => 46,  DIRECT (one)
           'DA' => 3,   DASH
           'DR' => 227, DIRECT
           'EX' => 19,  QUALIF
           'FC' => 23,  FRACT
           'H*' => 37,  [house]
           'HR' => 53,  ROAD
           'MP' => 5,   MILE
           'N*' => 4,   [number]
           'NU' => 522, NUMBER
           'OT' => 16,  ORD
           'P*' => 5,   [pobox]
           'PT' => 2,   TYPE
           'R*' => 4,   [ruralroute]
           'RR' => 7,   RR
           'SA' => 14,  PROV
           'T*' => 7,   [streetname]
           'TY' => 279, TYPE
           'W*' => 9,   [within]
           'WD' => 30,  UNITH
           'WI' => 17   UNITT
         };
$outtok = {
            '1P' => 4,  number prefix
            'B*' => 7,  @building
            'BD' => 1,  prefix directional
            'BI' => 3,  number
            'BN' => 231,street name
            'BS' => 12, number suffix
            'BT' => 97, suffix type
            'BX' => 9,  type
            'BY' => 3,  type
            'DB' => 13, suffix directional
            'EI' => 36, extra info
            'EX' => 17, extension
            'H*' => 37, @house
            'H1' => 18, house num 1
            'H2' => 40, house num 2
            'HN' => 247,house num
            'HS' => 61, house number suffix
            'NA' => 511,street name
            'NB' => 53, number
            'P*' => 5,  @pobox
            'P1' => 50, house number prefix
            'P2' => 32, house number prefix 2
            'PD' => 118,prefix directional
            'PT' => 96, prefix type
            'R*' => 4,  @ruralroute
            'RN' => 5,  rr number
            'RR' => 7,  rr description
            'SD' => 47, suffix directional
            'ST' => 169,suffix type
            'T*' => 7,  @streetname
            'TB' => 15, prefix type
            'W*' => 9,  @within
            'WD' => 30, within description
            'WI' => 142,within identifier
            'XN' => 17  number
          };
=cut

